### PR TITLE
fix: ogranization API actualized

### PR DESCRIPTION
**Pull request by aegoroff**
Ogranization API is not actual now. API get methods return CasdoorResponse now but SDK expects CasdoorOrganization or IEnumerable<CasdoorOrganization> respectively

### CODE REVIEW

**Comment by hsluoyz** [comment]
@aegoroff All Casdoor APIs return Response object now. Can you fix all functions in this SDK?

**Comment by aegoroff** [comment]
@hsluoyz i can but i'm not sure about all API methods. For example https://github.com/casdoor/casdoor/blob/master/controllers/application.go GetApplication still returns Application but not Response. 

I saw this PR https://github.com/casdoor/casdoor/pull/2036 but it's not merged yet

**Comment by hsluoyz** [comment]
@aegoroff OK,

can you resolve the conflict?

image

**Comment by aegoroff** [comment]
@hsluoyz done. I've resolved all confilicts

**Comment by hsluoyz** [comment]
@aegoroff plz fix conflicts:

image

**Pull request merged**
