### PR TITLE
fix: incorrect CasdoorModel and incorrect enforce methods params

### PR DESCRIPTION
**Pull request by d1mak3**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@d1mak3 can you please test your code to make sure it works first? Can you provide the test result?

**Comment by d1mak3** [comment]
@hsluoyz sowwy. It's mostly modifications because I keep forgetting to add something from api. Or in such situation I had old version of casdoor and there was no IsEnabled in Model. But yeah I'll pay more attention sorry once again

**Comment by hsluoyz** [comment]
@d1mak3 for this time (this PR), have you tested your code to make sure it works locally first? If yes, can you provide the test result?

**Comment by d1mak3** [comment]
@hsluoyz hi! This pr has many mistakes and I decided to fully rewrite it. Can I close this one? And ofc I will add test results in comments on new pr

**Pull request closed without merging**
