### PR TITLE
feat: add roleModel, permissionModel, roleApi, permissionApi

### PR DESCRIPTION
**Pull request by ISulimanov**
example of usage:

var roles = await client.GetRolesAsync();
var perm = (await client.GetPermissionsByRoleAsync(roles.First().Name))?.Data;
var persmissions = await client.GetPermissionsAsync();

### CODE REVIEW

**Comment by hsluoyz** [comment]
@ISulimanov fix:

image

**Comment by hsluoyz** [comment]
@ISulimanov I think this one is the key:

image

**Comment by ISulimanov** [comment]
@hsluoyz looks like was a problem with my email commits, i've create the new one PR

**Comment by hsluoyz** [comment]
@ISulimanov plz re-use the same PR, see: https://casdoor.org/docs/contributing#modify-prs

**Pull request closed without merging**
