### PR TITLE
fix: fix typo and specified owner in methods that used _options.Organ…

### PR DESCRIPTION
**Pull request by d1mak3**

### CODE REVIEW

**Comment by sagilio** [comment]
Hi, May I ask what is different about #65?

**Comment by d1mak3** [comment]
> Hi, May I ask what is different about #65?

Hello. Nothing much to be honest, just different controllers, because I didn't see this thing in other controllers at first. Should I create new PR with such fix in every controller and close this one and #65?

**Comment by sagilio** [comment]
> > Hi, May I ask what is different about #65?
> 
> Hello. Nothing much to be honest, just different APIs, because I didn't see this thing in other APIs at first. Should I create new PR with such fix in every API and close this one and #65?

I find that #65 includes all changes in this PR. We may merge the #65 and close this PR.

**Comment by d1mak3** [comment]
> > > Hi, May I ask what is different about #65?
> > 
> > 
> > Hello. Nothing much to be honest, just different APIs, because I didn't see this thing in other APIs at first. Should I create new PR with such fix in every API and close this one and #65?
> 
> I find that #65 includes all changes in this PR. We may merge the #65 and close this PR.

My bad, it does include all changes, sorry. So yeah that would be great tyvm

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casdoor/casdoor-dotnet-sdk/pull/65

**Pull request closed without merging**
